title: Continental Communist
description: An American perspective on scientific socialism.
url: "https://www.continentalcommunist.com"
baseurl: ""

author: Continental Communist

theme: minima

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

show_excerpts: true
