title: Continental Communist
description: Essays, commentary, and analysis.
url: "https://www.continentalcommunist.com"
baseurl: ""

author: Continental Communist

theme: minima

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md

show_excerpts: true
