#!/usr/bin/env node

import { createHash } from "node:crypto";
import { readFile, readdir } from "node:fs/promises";
import { join } from "node:path";

const ROOT = new URL("../", import.meta.url).pathname;
const manifest = JSON.parse(await readFile(join(ROOT, "scripts/data/marx_mia_core.json"), "utf8"));
const errors = [];
const expectedChapters = new Set();

const sha256 = (value) => createHash("sha256").update(value).digest("hex");

function frontMatter(source, path) {
  const match = source.match(/^---\n([\s\S]*?)\n---\n/);
  if (!match) {
    errors.push(`${path}: missing front matter`);
    return {};
  }

  const data = {};
  for (const line of match[1].split("\n")) {
    const separator = line.indexOf(":");
    if (separator === -1) continue;
    const key = line.slice(0, separator);
    const rawValue = line.slice(separator + 1).trim();
    try {
      data[key] = JSON.parse(rawValue);
    } catch {
      errors.push(`${path}: ${key} is not deterministic JSON-compatible YAML`);
    }
  }
  return data;
}

for (const work of manifest.works) {
  const bookPath = join(ROOT, "_books", `${work.slug}.md`);
  let bookSource;
  try {
    bookSource = await readFile(bookPath, "utf8");
  } catch {
    errors.push(`_books/${work.slug}.md: missing imported work record`);
    continue;
  }

  const book = frontMatter(bookSource, `_books/${work.slug}.md`);
  if (book.layout !== "book") errors.push(`_books/${work.slug}.md: layout must be book`);
  if (book.source_url !== work.source_index) errors.push(`_books/${work.slug}.md: source URL drifted from manifest`);
  if (book.rights_basis !== work.rights_basis) errors.push(`_books/${work.slug}.md: rights basis drifted from manifest`);
  if (book.license_url !== manifest.archive.license_url) errors.push(`_books/${work.slug}.md: license URL is missing or incorrect`);
  if (book.rights_reviewed !== "2026-09-01") errors.push(`_books/${work.slug}.md: rights review date is missing`);

  for (const page of work.pages) {
    const relative = `_text_chapters/${work.slug}/${page.slug}.md`;
    const path = join(ROOT, relative);
    expectedChapters.add(relative);
    let source;
    try {
      source = await readFile(path, "utf8");
    } catch {
      errors.push(`${relative}: missing imported section`);
      continue;
    }

    const data = frontMatter(source, relative);
    const expectedSourceUrl = new URL(page.path, work.source_index).href;
    const generatedMarker = "<!-- Generated by scripts/import_mia_texts.mjs. Edit the manifest or importer, not this file. -->";
    const body = source.split(generatedMarker)[1]?.trim();

    if (data.layout !== "text-chapter") errors.push(`${relative}: layout must be text-chapter`);
    if (data.parent_text !== work.slug) errors.push(`${relative}: parent text is incorrect`);
    if (data.source_url !== expectedSourceUrl) errors.push(`${relative}: source URL drifted from manifest`);
    if (data.source_work_url !== work.source_index) errors.push(`${relative}: source-work URL drifted from manifest`);
    if (data.rights_basis !== work.rights_basis) errors.push(`${relative}: rights basis drifted from manifest`);
    if (data.license_url !== manifest.archive.license_url) errors.push(`${relative}: license URL is missing or incorrect`);
    if (!/^[a-f0-9]{64}$/.test(data.source_sha256 ?? "")) errors.push(`${relative}: source fingerprint is missing`);
    if (!body || data.content_sha256 !== sha256(body)) errors.push(`${relative}: generated content fingerprint does not match`);
    if (!data.source_url?.startsWith("https://www.marxists.org/")) errors.push(`${relative}: source must be an HTTPS MIA URL`);
    if (/MECW File No Longer Available|Copyright:<\/span>|Fair Use:<\/span>/.test(source)) {
      errors.push(`${relative}: contains a blocked rights marker`);
    }
    if (/<img\b/i.test(body ?? "")) errors.push(`${relative}: imported images require a separate review`);
  }
}

async function markdownFiles(directory, prefix = "") {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const relative = join(prefix, entry.name);
    if (entry.isDirectory()) files.push(...(await markdownFiles(join(directory, entry.name), relative)));
    else if (entry.name.endsWith(".md")) files.push(relative);
  }
  return files;
}

for (const relative of await markdownFiles(join(ROOT, "_text_chapters"))) {
  const manifestPath = `_text_chapters/${relative}`;
  if (!expectedChapters.has(manifestPath)) errors.push(`${manifestPath}: generated section is not present in the approved manifest`);
}

if (errors.length) {
  console.error("Primary-text library validation failed:");
  for (const error of errors) console.error(`- ${error}`);
  process.exit(1);
}

console.log(`Primary-text library valid: ${manifest.works.length} rights-reviewed works and ${expectedChapters.size} locally hosted sections.`);
